# vim:fileencoding=utf-8:ft=yaml

# Choose the backend terminal to run neovim in.
# Current supported terminals: alacritty, urxvt, kitty.
#backend: urxvt

# path to backend executable file
# NOTE: requires a backend key
# NOTE: old key exe_path is now deprecated but can still be used
#term_exe_path: /path/to/urxvt

# Specify the Neovim executable path.
# NOTE: nvim will be used if not specified
# NOTE: For windows, e.g.: C:\tools\neovim\Neovim\bin\nvim.exe
#nvim_exe_path: /path/to/nvim

# The fonts to be used. Multi fonts can be supplied.
# The first one will be set as the major font. Others will be set as
# fallback fonts according to the given orders if possible.
# NOTE: Not all backends support fallback font.
#fonts:
#  - Source Code Pro
#  - monofur

# The font size to be used.
#
#font_size: 12

# Set to true if the terminal's default configuration should be loaded
# first. Other glrnvim configurations will overwrite the terminal settings
# if they are set in config.yml.
# urxvt is not impacted by this setting. It always load resources according
# to the defined orders.
#load_term_conf: false
